var generateQuoteButton = document.querySelector('.button');
var quoteText = document.getElementById('quote');
var authorText = document.getElementById('author');

var quotes = [
    {"quote": "Be realistic; demand the impossible.", "author": "Che Guevara"},
    {"quote": "The most important thing is not to win, but to participate.", "author": "Pierre de Coubertin"},
    {"quote": "The world belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt"},
    {"quote": "He who risks nothing, has nothing.", "author": "Gaius Julius Caesar"},
    {"quote": "Everyone who teaches something, teaches themselves.", "author": "Ralph Waldo Emerson"},
    {"quote": "Those who want to, look for opportunities; those who don’t, look for reasons.", "author": "Ivan Sidorov"},
    {"quote": "We cannot change the direction of the wind, but we can adjust our sails.", "author": "Jackson Brown"},
    {"quote": "Everything we are is the result of our thoughts.", "author": "Buddha"},
    {"quote": "Don't be afraid of perfection—you’ll never reach it.", "author": "Salvador Dalí"},
    {"quote": "Life is what happens while you are busy making other plans.", "author": "John Lennon"},
    {"quote": "It's never too late to be what you might have been.", "author": "George Eliot"},
    {"quote": "If you want to change the world, start with yourself.", "author": "Mahatma Gandhi"},
    {"quote": "We see the world not as it is, but as we are.", "author": "Francis Bacon"},
    {"quote": "True love is not what we feel, but what we do.", "author": "Antoine de Saint-Exupéry"},
    {"quote": "Never give up, even if everything seems lost.", "author": "Winston Churchill"},
    {"quote": "One cannot become rich without first becoming spiritually rich.", "author": "Robert Kiyosaki"},
    {"quote": "If you want to do something, do it now.", "author": "Mark Twain"},
    {"quote": "We can all make the world a better place if we try.", "author": "Mother Teresa"},
    {"quote": "Great ideas start with great imagination.", "author": "Albert Einstein"},
    {"quote": "The less you have, the more you appreciate what you have.", "author": "Lao Tzu"},
    {"quote": "Victory is not always the most important thing, but striving for victory is.", "author": "Alexandre Dumas"},
    {"quote": "Every day is a new opportunity to change your life.", "author": "George S. Patton"},
    {"quote": "Do what you love, and you’ll never work a day in your life.", "author": "Confucius"},
    {"quote": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt"},
    {"quote": "The journey of a thousand miles begins with one step.", "author": "Lao Tzu"},
    {"quote": "Success is not the key to happiness. Happiness is the key to success.", "author": "Albert Schweitzer"},
    {"quote": "Your time is limited, don't waste it living someone else's life.", "author": "Steve Jobs"},
    {"quote": "Believe you can and you’re halfway there.", "author": "Theodore Roosevelt"},
    {"quote": "It does not matter how slowly you go, as long as you do not stop.", "author": "Confucius"},
    {"quote": "In three words I can sum up everything I've learned about life: it goes on.", "author": "Robert Frost"},
    {"quote": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"quote": "The best way to predict the future is to invent it.", "author": "Alan Kay"},
    {"quote": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky"},
    {"quote": "The only impossible journey is the one you never begin.", "author": "Tony Robbins"},
    {"quote": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt"},
    {"quote": "Happiness is not something ready-made. It comes from your own actions.", "author": "Dalai Lama"},
    {"quote": "The purpose of our lives is to be happy.", "author": "Dalai Lama"},
    {"quote": "We may encounter many defeats but we must not be defeated.", "author": "Maya Angelou"},
    {"quote": "Life is short, and it is up to you to make it sweet.", "author": "Sarah Louise Delany"},
    {"quote": "The only way to have a friend is to be one.", "author": "Ralph Waldo Emerson"},
    {"quote": "The mind is everything. What you think you become.", "author": "Buddha"},
    {"quote": "Don't watch the clock; do what it does. Keep going.", "author": "Sam Levenson"},
    {"quote": "You can’t go back and change the beginning, but you can start where you are and change the ending.", "author": "C.S. Lewis"},
    {"quote": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill"},
    {"quote": "Life is what happens when you’re busy making other plans.", "author": "John Lennon"},
    {"quote": "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.", "author": "Ralph Waldo Emerson"},
    {"quote": "You only live once, but if you do it right, once is enough.", "author": "Mae West"},
    {"quote": "If you want to lift yourself up, lift up someone else.", "author": "Booker T. Washington"},
    {"quote": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs"},
    {"quote": "The best revenge is massive success.", "author": "Frank Sinatra"},
    {"quote": "I have not failed. I've just found 10,000 ways that won't work.", "author": "Thomas A. Edison"},
    {"quote": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau"},
    {"quote": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt"},
    {"quote": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson"},
    {"quote": "Do not wait to strike till the iron is hot, but make it hot by striking.", "author": "William Butler Yeats"},
    {"quote": "The only person you are destined to become is the person you decide to be.", "author": "Ralph Waldo Emerson"},
    {"quote": "Life isn’t about finding yourself. Life is about creating yourself.", "author": "George Bernard Shaw"},
    {"quote": "Everything has beauty, but not everyone can see.", "author": "Confucius"},
    {"quote": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "author": "Aristotle"},
    {"quote": "The greatest glory in living lies not in never falling, but in rising every time we fall.", "author": "Nelson Mandela"},
    {"quote": "The unexamined life is not worth living.", "author": "Socrates"},
    {"quote": "To live is the rarest thing in the world. Most people exist, that is all.", "author": "Oscar Wilde"},
    {"quote": "Life is really simple, but we insist on making it complicated.", "author": "Confucius"},
    {"quote": "Life is what we make it, always has been, always will be.", "author": "Grandma Moses"},
    {"quote": "The only thing we have to fear is fear itself.", "author": "Franklin D. Roosevelt"},
    {"quote": "It is never too late to be what you might have been.", "author": "George Eliot"},
    {"quote": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson"},
    {"quote": "The secret of getting ahead is getting started.", "author": "Mark Twain"},
    {"quote": "The only way to have a friend is to be one.", "author": "Ralph Waldo Emerson"},
    {"quote": "A journey of a thousand miles begins with a single step.", "author": "Lao Tzu"},
    {"quote": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar"},
    {"quote": "It does not do to dwell on dreams and forget to live.", "author": "J.K. Rowling"},
    {"quote": "We do not remember days; we remember moments.", "author": "Cesare Pavese"},
    {"quote": "The purpose of our lives is to be happy.", "author": "Dalai Lama"},
    {"quote": "The best preparation for tomorrow is doing your best today.", "author": "H. Jackson Brown Jr."},
    {"quote": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi"},
    {"quote": "The greatest wealth is to live content with little.", "author": "Plato"},
    {"quote": "Happiness is not by chance, but by choice.", "author": "Jim Rohn"},
    {"quote": "The difference between a successful person and others is not a lack of strength, not a lack of knowledge, but rather a lack in will.", "author": "Vince Lombardi"},
    {"quote": "Life is what happens when you're busy making other plans.", "author": "John Lennon"},
    {"quote": "Success is not in what you have, but who you are.", "author": "Bo Bennett"},
    {"quote": "Act as if what you do makes a difference. It does.", "author": "William James"},
    {"quote": "You only live once, but if you do it right, once is enough.", "author": "Mae West"},
    {"quote": "Life is short, and it is up to you to make it sweet.", "author": "Sarah Louise Delany"},
    {"quote": "You can’t help everyone, but everyone can help someone.", "author": "Ronald Reagan"},
    {"quote": "Don't count the days, make the days count.", "author": "Muhammad Ali"},
    {"quote": "You get in life what you have the courage to ask for.", "author": "Oprah Winfrey"},
    {"quote": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein"},
    {"quote": "The best way to predict your future is to create it.", "author": "Peter Drucker"},
    {"quote": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"quote": "You must do the things you think you cannot do.", "author": "Eleanor Roosevelt"},
    {"quote": "If you want to achieve greatness stop asking for permission.", "author": "Anonymous"},
    {"quote": "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.", "author": "Christian D. Larson"}
];


function getRandomInt(max) {
    return Math.floor(Math.random() * (max + 1));
}

function getQuote() {
    const randomNumber = getRandomInt(quotes.length - 1);
    quoteText.textContent = quotes[randomNumber].quote;
    authorText.textContent = `— ${quotes[randomNumber].author}`;
}

generateQuoteButton.addEventListener("click", getQuote);